endpoint: "https://api.openweathermap.org/data/2.5/onecall/timemachine"
database:
  host: postgres-db
  user: sramirez
  pass: sramirez1234
  db: metadata
days: 5
unit: metric
api: a90258c97e50044075e289056fe1b24f
locations:
  - Tierra blanca Veracruz
  - Guadalajara Jalisco
  - Houston Texas
  - Monterrey Nuevo Leon
  - Las Vegas
  - New York
  - Boston
  - Kansas City
  - Phoenix
  - Seattle